import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  content: {
    display: 'flex',
    width: '100%',
    flexDirection: 'column',
    marginTop: 50,
    paddingHorizontal: 21,
    gap: 13,
    paddingBottom: 120, // Увеличил отступ снизу для лучшей видимости кнопок
  },
  topHeaderSection: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 24,
  },
  cardTitleContainer: {
    flex: 1,
  },
  cardTitle: {
    color: '#000',
    fontFamily: 'Inter',
    fontSize: 26,
    fontStyle: 'normal',
    fontWeight: '700',
    textAlign: 'left',
  },
  cardSubtitle: {
    color: '#50B848',
    fontFamily: 'Inter',
    fontSize: 26,
    fontStyle: 'normal',
    fontWeight: '700',
    textAlign: 'left',
    marginTop: 4,
  },
  settingsButton: {
    width: 63,
    height: 37,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
  },
  pageHeaderSection: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
  },
  backButton: {
    width: 63,
    height: 37,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 20,
    backgroundColor: '#fff',
    flexDirection: 'row',
    marginRight: 16,
  },
  pageTitle: {
    color: '#000',
    fontFamily: 'Inter',
    fontSize: 26,
    fontStyle: 'normal',
    fontWeight: '700',
    lineHeight: 32,
    textAlign: 'left',
  },
  section: {
    marginBottom: 24,
  },
  sectionTitle: {
    color: '#454545',
    fontFamily: 'Inter',
    fontSize: 18,
    fontStyle: 'normal',
    fontWeight: '700',
    lineHeight: 22,
    marginBottom: 20,
  },
  tasksList: {
    gap: 13,
  },
  completedTaskCard: {
    height: 83,
    paddingHorizontal: 30,
    paddingVertical: 25,
    backgroundColor: '#FFF',
    borderRadius: 26,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    alignSelf: 'stretch',
    borderWidth: 2,
    borderColor: '#50B848',
  },
  unverifiedTaskCard: {
    height: 83,
    paddingHorizontal: 30,
    paddingVertical: 25,
    backgroundColor: '#FFF',
    borderRadius: 26,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    alignSelf: 'stretch',
    borderWidth: 2,
    borderColor: '#FFA500',
  },
  pendingTaskCard: {
    height: 83,
    paddingHorizontal: 30,
    paddingVertical: 25,
    backgroundColor: '#FFF',
    borderRadius: 26,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    alignSelf: 'stretch',
    borderWidth: 2,
    borderColor: '#FBADAD',
  },
  taskText: {
    color: '#454545',
    fontFamily: 'Inter',
    fontSize: 16,
    fontStyle: 'normal',
    fontWeight: '700',
    lineHeight: 19,
    flex: 1,
  },
  earnText: {
    color: '#454545',
    fontFamily: 'Inter',
    fontSize: 16,
    fontStyle: 'normal',
    fontWeight: '700',
    textAlign: 'right',
  },
  checkIconContainer: {
    width: 33,
    height: 33,
    borderRadius: 16.5,
    backgroundColor: '#50B848',
    justifyContent: 'center',
    alignItems: 'center',
  },
  pendingIconContainer: {
    width: 33,
    height: 33,
    borderRadius: 16.5,
    backgroundColor: '#FFA500',
    justifyContent: 'center',
    alignItems: 'center',
  },
  pendingIcon: {
    fontSize: 18,
    color: '#FFF',
  },
}); 